// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/swisscom/korp/docker_utils"
	"github.com/swisscom/korp/pull"
	"sigs.k8s.io/kustomize/pkg/image"
	"sync"
)

var (
	lockIoMockLoadKustomizationFile sync.RWMutex
	lockIoMockOpenDockerClient      sync.RWMutex
)

// Ensure, that IoMock does implement Io.
// If this is not the case, regenerate this file with moq.
var _ pull.Io = &IoMock{}

// IoMock is a mock implementation of Io.
//
//     func TestSomethingThatUsesIo(t *testing.T) {
//
//         // make and configure a mocked Io
//         mockedIo := &IoMock{
//             LoadKustomizationFileFunc: func(kstPath string) ([]image.Image, error) {
// 	               panic("mock out the LoadKustomizationFile method")
//             },
//             OpenDockerClientFunc: func() (docker_utils.DockerClient, error) {
// 	               panic("mock out the OpenDockerClient method")
//             },
//         }
//
//         // use mockedIo in code that requires Io
//         // and then make assertions.
//
//     }
type IoMock struct {
	// LoadKustomizationFileFunc mocks the LoadKustomizationFile method.
	LoadKustomizationFileFunc func(kstPath string) ([]image.Image, error)

	// OpenDockerClientFunc mocks the OpenDockerClient method.
	OpenDockerClientFunc func() (docker_utils.DockerClient, error)

	// calls tracks calls to the methods.
	calls struct {
		// LoadKustomizationFile holds details about calls to the LoadKustomizationFile method.
		LoadKustomizationFile []struct {
			// KstPath is the kstPath argument value.
			KstPath string
		}
		// OpenDockerClient holds details about calls to the OpenDockerClient method.
		OpenDockerClient []struct {
		}
	}
}

// LoadKustomizationFile calls LoadKustomizationFileFunc.
func (mock *IoMock) LoadKustomizationFile(kstPath string) ([]image.Image, error) {
	if mock.LoadKustomizationFileFunc == nil {
		panic("IoMock.LoadKustomizationFileFunc: method is nil but Io.LoadKustomizationFile was just called")
	}
	callInfo := struct {
		KstPath string
	}{
		KstPath: kstPath,
	}
	lockIoMockLoadKustomizationFile.Lock()
	mock.calls.LoadKustomizationFile = append(mock.calls.LoadKustomizationFile, callInfo)
	lockIoMockLoadKustomizationFile.Unlock()
	return mock.LoadKustomizationFileFunc(kstPath)
}

// LoadKustomizationFileCalls gets all the calls that were made to LoadKustomizationFile.
// Check the length with:
//     len(mockedIo.LoadKustomizationFileCalls())
func (mock *IoMock) LoadKustomizationFileCalls() []struct {
	KstPath string
} {
	var calls []struct {
		KstPath string
	}
	lockIoMockLoadKustomizationFile.RLock()
	calls = mock.calls.LoadKustomizationFile
	lockIoMockLoadKustomizationFile.RUnlock()
	return calls
}

// OpenDockerClient calls OpenDockerClientFunc.
func (mock *IoMock) OpenDockerClient() (docker_utils.DockerClient, error) {
	if mock.OpenDockerClientFunc == nil {
		panic("IoMock.OpenDockerClientFunc: method is nil but Io.OpenDockerClient was just called")
	}
	callInfo := struct {
	}{}
	lockIoMockOpenDockerClient.Lock()
	mock.calls.OpenDockerClient = append(mock.calls.OpenDockerClient, callInfo)
	lockIoMockOpenDockerClient.Unlock()
	return mock.OpenDockerClientFunc()
}

// OpenDockerClientCalls gets all the calls that were made to OpenDockerClient.
// Check the length with:
//     len(mockedIo.OpenDockerClientCalls())
func (mock *IoMock) OpenDockerClientCalls() []struct {
} {
	var calls []struct {
	}
	lockIoMockOpenDockerClient.RLock()
	calls = mock.calls.OpenDockerClient
	lockIoMockOpenDockerClient.RUnlock()
	return calls
}
