apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: <a user name in base64>
  passphrase: <a passphrase in base64>
---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali-operator
  finalizers:
    - finalizer.kiali
spec:
  auth:
    strategy: login
  deployment:
    image_name: kiali/kiali
    image_version: v1.1.0
    namespace: istio-system
    secret_name: kiali
    accessible_namespaces:
      - "**"
  external_services:
    grafana:
      url: ""
    jaeger:
      url: ""
